package org.sertia.client;

import org.sertia.contracts.price.change.ClientTicketType;

import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class Constants {
    public static final String HOME_ONLINE_SCREENING = "צפיה ביתית ע\"י לינק";
    public static final String COMING_SOON = "בקרוב בסרטיה";
    public static final String CURRENTLY_AVAILABLE = "מופיע כעת";
    public static final String MOVIE_DETAILS = "פרטי הסרט";
    public static final String HELLO_SENTENCE = "ברוכה הבאה למערכת הסרטייה";
    public static final String BRANCH_MANAGER = "מנהלת הסניף";
    public static final String CINEMA_MANAGER = "מנהלת הרשת";
    public static final String MEDIA_MANAGER = "מנהלת המדיה";
    public static final String CUSTOMER_SUPPORT = "מנהלת שירות הלקוחות";
    public static final String BUY_STREAMING_LINK = "רכישת קישור";
    public static final String PRICE_CHANGE_APPROVAL = "אישור בקשות שינוי מחירים";
    public static final String STATISTICS_VIEW = "צפיה בדוחות";
    public static final String UPDATE_TAV_SAGOL_REGULATIONS = "עדכון מדיניות תו סגול";
    public static final String HADNLE_COMLAINTS = "טיפול בתלונות";
    public static final String REFUND_EMOUNT = "סכום לזיכוי";
    public static final String RESOLVE_COMPLAINT_BTN_TXT = "קבל תלונה";
    public static final String REJECT_COMPLAINT_BTN_TXT = "דחה תלונה";
    public static final String CANCEL_REGULATIONS = "ביטול הנחיות";
    public static final String ADD_OR_DELETE_SCREENING = "הוספה / הסרה של סרט";
    public static final String ADD_OR_DELETE_STREAMING = "הוספה / הסרה של חבילת צפיה ביתית";
    public static final String EDIT_PLAYING_TIME = "עדכון / הוספת מועדי הקרנה";
    public static final String EDIT_TICKETS_PRICE = "עדכון מחירים";
    public static final String REMOVE_STREAMING_LINK = "מחיקת חבילת צפיה";
    public static final String ADD_STREAMING_LINK = "הוספת חבילת צפיה";
    public static final String ADD_SCREENING = "הוספת הקרנה";
    public static final String APPROVE_CHANGE_REQUEST = "אשר בקשת שינוי";
    public static final String DENY_CHANGE_REQUEST = "דחה בקשה";
    public static final String MOVIE_NAME = "שם הסרט: ";
    public static final String REQUEST_ID = "מזהה בקשה: ";
    public static final String NEW_PRICE = "מחיר חדש: ";
    public static final String TICKET_TYPE = "סוג כרטיס: ";
    public static final String TAV_SAGOL_LABEL_TXT = "אין תקנות פעילות כעת, תוכלי להגדירן כעת";
    public static final String START_TAV_SAGOL_REGULATIONS_TXT = "החלי מדיניות תו סגול";
    public static final String NO_NEW_REQUESTS = "אין בקשות נוספות לאישור";
    public static final String SCREENING_TIME = "שעת הקרנה: ";
    public static final String HEBREW_MOVIE_NAME = "שם הסרט בעברית: ";
    public static final String RESULT_NUMBER = "תוצאה מספר: ";
    public static final String BRANCH_NAME = "שם סניף: ";
    public static final String CHOOSE_VALID_HOUR = "בחרי בבקשה שעת התחלה מתוך האפשרויות";
    public static final String CHOOSE_VALID_MIN = "בחרי בבקשה דקות בשעה";
    public static final String VIEW_WORKSTATION = "ברוכה הבאה לתחנת קצה בסניף ";
    public static final String AVAILABLE_MOVIES_IN_BRANCH = "סרטים המוקרנים בסניף";
    public static final String MISSING_LINK_ERROR = "נא הזיני את לינק הצפיה בסרט";
    public static final String STREAMING_LINK_AVAILABILITY_CHECKER = "בדיקת זמינות לינק לצפיה";
    public static final String YOUR_STREAMING_LINK_FOR_MOVIE = "חבילת הצפיה שלך לסרט: ";
    public static final String IS_AVAILABLE = " זמינה!";
    public static final String BUY_ONLINE_STREAMING_LINK = "רכישת לינק לצפיה ביתית";
    public static final String DATES_RANGE_INVALID_ERROR_MSG = "נא בחרי טווח תקין של תאריכים, תאריך ההתחלה חייב להיות לפני תאריך הסוף";
    public static final String PLEASE_CHOOSE_START_DATE_GREATER_THAN_TODAY = "נא בחרי תאריך התחלה מתקדם יותר מהיום";
    public static final String STREMING_LINK_INFO = "פרטי הקישור לצפיה ביתית שרכשת: \n לינק: ";
    public static final String START_TIME_END_TIME = "זמן התחלה - זמן סיום: ";
    public static final String PURCHASE_USING_CREDIT_CARD = "רכישה באמצעות כרטיס אשראי";
    public static final String PURCHASE_SUMMARY = "רכשת כרטיס/ים להקרנות ואלו הם פרטי ההזמנה: \n";
    public static final String CINEMA_NAME = "שם הקולנוע: ";
    public static final String HALL_NUMBER = "מספר האולם: ";
    public static final String FINAL_PRICE = "מחיר סופי: ";
    public static final String VOUCHER_ID = "מזהה ווצ'ר: ";
    public static final String TICKETS = "כרטיסים: מספר הכרטיס = <שורה, מספר כיסא>";
    public static final String FATAL_SERVER_ERROR = "שגיאת שרת חמורה";
    public static final String CLIENT_DATA_FOR_STREAMING_LINK_IS_NOT_SET = "לא נקבע מידע לקוח עבור לינק צפיה זה, נא פנה לשירות הלקוחות";
    public static final String CVV_HINT = "מלא בבקשה את ה-CVV שלך, באורך 3 תווים";
    public static final String CREDIT_CARD_PROVIDER_HINT = "בחר את ספק כרטיס האשראי שלך מבין האפשרויות";
    public static final String VOUCHER_INFO_ERROR = "בירור מידע כרטיסיה";
    public static final String COULDNT_FETCH_VOUCHER_DATA = "שגיאה בקריאת פרטי מידע על הכרטיסייה, פירוט השגיאה: ";
    public static final String PURCHASE_MOVIE_TICKETS = "רכישת כרטיסים לסרט";
    public static final String HALL_IS_FULL = "האולם מלא, לא ניתן לסיים את תהליך הרכישה";
    public static final String PREPAID_BALANCE_CHECK = "בירור יתרת כרטיסיה";
    public static final String PREPAID_BALANCE_CHECK_FAILED = PREPAID_BALANCE_CHECK + " נכשל, הסיבה: ";
    public static final String PLEASE_INSERT_VALID_VOUCHER_ID = "נא הזן מזהה כרטיסיה תקין";
    public static final String PAYMENT_WITH_VOUCHER = "תשלום באמצעות כרטיסיה";
    public static final String PAYMENT_WITH_VOUCHER_FAILED = "אנו מתנצלים, איך היתרה בכרטיסיה היא כרגע: ";
    public static final String STREAMING_LINK_TITLE = "צפיה בלינק צפיה ביתית";
    public static final String STREAMING_LINK_ERROR_MSG = "הלינק עוד לא זמין לצפיה, הוא זמין בזמנים הבאים: ";
    public static final String CREDIT_CARD_FAILURE = "נא הזיני מחדש מספר כרטיס אשראי וספק";
    public static final String INPUT_VALIDATIONS_ERROR = "שגיאות תקינות קלט";
    public static final String LOGIN_ATTEMPT_TITLE = "נסיון התחברות למערכת הסרטיה";
    public static final String MUST_INSERT_USER_NAME_AND_PASSWORD = "נא הזיני שם משתמש וסיסמא";
    public static final String MUST_INSERT_USER_NAME = "נא הזיני שם משתמש";
    public static final String MUST_INSERT_PASSWORD = "נא הזיני סיסמא";
    public static final String LOGIN_FAILED = "שם משתמש או סיסמא אינם נכונים";
    public static final String PRIMARY_CONTROLLER = "טעינת מסך ראשי";
    public static final String CINIMAS_LIST_FETCH_ERROR = "נסיון שליפת בתי הקולנוע של הרשת נכשל";
    public static final String CINIMA_BRANCHES_QUERY = "שליפת סניפי הסרטיה";
    public static final String SEARCH_MOVIES_QUERY = "נסיון חיפוש סרטים";
    public static final String MUST_SPECIFY_SEARCH_PARAMS = "עליך לציין מאפייני חיפוש";
    public static final String SPECIFIC_BRANCH = "SPECIFIC_BRANCH";
    public static final String APPROVE_PRICE_CHANGE_REQUEST = "אישור בקשת שינוי מחיר";
    public static final String FETCH_MOVIE_ERROR = "נסיון שליפת סרטי הרשת נכשל";
    public static final String CATALOG_FETCH_ERROR = "נסיון שליפת קטלוג הסרטים נכשל, להלן הסיבה: ";
    public static final String PRICE_CHANGE_REQUEST_APPROVAL_FINISHED_SUCCESSFULLY = "בקשת שינוי מחיר אושרה והשתנתה בהצלחה";
    public static final String PRICE_CHANGE_REQUEST = "בקשת שינוי מחיר";
    public static final String PRICE_CHANGE_REQUEST_ENDED_SUCCESSFULLY = "בקשת שינוי מחיר נשלחה בהצלחה";
    public static final String TAV_SAGOL_REGULATIONS_SET_SUCCESSFULLY = "תקנות תו סגול עודנו בהצלחה!";
    public static final String MAX_AMOUNT_OF_PEOPLE_ERROR = "כמות אנשים מקסימלית באולם חייבת להיות מספר";
    public static final String CHOOSE_DATES_IN_INCEREMENTAL_ORDER = "נא בחר תאריכים עוקבים, כך שהראשון לפני השני";
    public static final String REMOVE_FROM_SERTIA_SYSTEM = "מחיקה ממערכת הסרטייה";
    public static final String REMOVE_ENDED_SUCCESSFULLY = "מחיקה ממערכת הסרטיה הושלמה בהצלחה";
    public static final String MOVIES_CATALOG_FETCH = "שליפת קטלוג הסרטים של הסרטיה";
    public static final String MUST_SPECIFIY_A_MOVIE_TO_REMOVE = "נא בחרי סרט למחיקה";
    public static final String COVID_NOTIFICATION = "התראת קורונה";
    public static final String SEATS_BY_SYSTEM_DECISION_MSG = "עקב מגבלות תו-סגול, אנחנו נבחר את המושבים עבורך";
    public static final String COVID_REGULATIONS_TITLE = "הגבלות תו סגול";
    public static final String NUMBER_OF_TICKETS_MUST_BE_A_NUMBER = "מספר כרטיסים צריך להיות מספר";
    public static final String PURCHASE_FAILED_SINCE_THERE_ARE_NO_LEFT_SEATS_AT_HALL = "לא ניתן להשלים את הרכישה מאחר ואין מספיק מושבים פנוים באולם";
    public static final String EXCEEDED_TAV_SAGOL_MAX_ALLOWED_PEOPLE_REGULATIONS = "לא ניתן לקנות כמות כרטיסים זאת מאחר וקיימת הגבלת תו סגול על כמות מקסימלית של אנשים באולם";
    public static final String COMPLAINTS_APPROVAL_PROCESS = "אישור או דחיית תלונות";
    public static final String COMPLAINT_APPROVED = "התלונה נסגרה בהצלחה!";
    public static final String CREATE_COMPLAINT = "תהליך הגשת תלונה ";
    public static final String COMLAINT_SENT_SUCCESSFULLY = "תלונתך נשלחה בהצלחה ותטופל תוך 24 שעות!";
    public static final String REFUND_AMOUNT_VALIDATION = "נא הזיני סכום לזיכוי";
    public static final String COMPLAINT_DESCRIPTION_MISSING = "נא פרטי אודות תלונתך";
    public static final String ADD_MOVIE = "הוספת סרט";
    public static final String ADD_MOVIE_COMPLETED_SUCCESSFULLY = "הסרט התווסף בהצלחה וכעת ניתן להוסיף הקרנות";
    public static final String MOVIE_DETAILS_INVALID = "נתוני הסרט אינם תקינים";
    public static final String CANCEL_PURCHASE = "ביטול רכישה";
    public static final String CANCEL_PURCHASE_ENDED_SUCCESSFULLY = "ביטול הרכישה הסתיים בהצלחה, להלן סכום הזיכוי: ";
    public static final String SCREENING = "הקרנה";
    public static final String STREAMING = "חבילת צפייה ביתית";
    public static final String PLEASE_CHOOSE_PURCHASE_OPTION = "נא צייני סוג רכישה";
    public static final String BUYING_PREPAID_TICKETS_FROM_SERTIA = "רכישת כרטיסיה מהסרטיה";
    public static final String FULL_NAME_EXCEPTION_EXPLANATION = "נא הזיני שם מלא";
    public static final String ID_EXCEPTION_EXPLANATION = "נא הזיני את תעודת הזהות שלך, באורך 9 תווים";
    public static final String EMAIL_EXCEPTION_EXPANATION = "נא הזיני מייל תקין";
    public static final String INVALID_PURCHASE_ID = "מזהה קניה לא תקין, הוא צריך להיות מספר";
    public static final String PHONE_VALIDATION_EXPLANATION = "נא הזיני מספר טלפון תקין, באורך 10 תווים ללא -";
    public static final String INVALID_USERNAME = "שם משתמש לא תקין, מצפים למחרוזת באורך 5 עד 29 תווים";
    public static final String ADD_SCREENING_TO_MOVIE = "הוספת הקרנות לסרט בסרטיה";
    public static final String SCREENING_ADDED_SUCCESSFULLY = "הקרנה הוספה בהצלחה!";
    public static final String ADD_STREAMING_TO_MOVIE = "הוספה או הסרת חבילת צפיה מסרט";
    public static final String ENTER_VALID_STREAMING_PRICE = "הזיני מחיר תקין לחבילת הצפיה";
    public static final String STREAMING_ADDED_SUCCESSFULLY = "חבילת הצפיה הוספתה בהצלחה";
    public static final String REMOVE_SCREENING = "מחיקת הקרנה";
    public static final String REMOVE_SCREENING_ENDED_SUCCESSFULLY = "מחיקת הקרנה הסתיימה בהצלחה";
    public static final String EDIT_SCREENING_TIME = "עריכת זמני הקרנה";
    public static final String EDIT_SCREENING_TIME_ENDED_SUCESSFULLY = "עריכת זמני הקנה הסתיימה בהצלחה";

    public static final Set<Integer> HOURS = IntStream.rangeClosed(0, 23).boxed().collect(Collectors.toSet());
    public static final Set<Integer> MINUTES = IntStream.rangeClosed(0, 59).boxed().collect(Collectors.toSet());

    public static final HashMap<String, String> TICKET_TYPE_TRANSLATIONS = new HashMap<>(){{
            put(ClientTicketType.Screening.name(), "הקרנה");
            put(ClientTicketType.Streaming.name(), "חבילת צפיה");
            put(ClientTicketType.Voucher.name(), "כרטיסיה");
    }};
}